# Generated by Django 3.2.23 on 2023-11-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_zsad'),
        ('users', '0002_auto_20231124_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rel_zsad_1_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rel_zsad_1_1', to='home.zsad'),
        ),
    ]
